language: php

env:
  - LARAVEL_VERSION=6.*

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 7.2
      env: LARAVEL_VERSION=6.*
    - php: 7.2
      env: LARAVEL_VERSION=5.6.*

before_install:
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update

install:
  - travis_retry composer update --no-interaction --prefer-dist --no-suggest
